REPOSITORY_INITIALIZED = "repository.initialized"
REPOSITORY_INVENTORY_UPDATED = "repository.inventory.updated"
REPOSITORY_SUBSYSTEM_ADDED = "repository.subsystem.added"
REPOSITORY_SUBSYSTEM_REMOVED = "repository.subsystem.removed"
REPOSITORY_AUTHORITY_REGISTERED = "repository.authority.registered"
REPOSITORY_AUDIT_COMPLETED = "repository.audit.completed"
REPOSITORY_COLLISION_DETECTED = "repository.collision.detected"

REPOSITORY_DNA_EVENTS = [
    REPOSITORY_INITIALIZED,
    REPOSITORY_INVENTORY_UPDATED,
    REPOSITORY_SUBSYSTEM_ADDED,
    REPOSITORY_SUBSYSTEM_REMOVED,
    REPOSITORY_AUTHORITY_REGISTERED,
    REPOSITORY_AUDIT_COMPLETED,
    REPOSITORY_COLLISION_DETECTED,
]
