from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "nimble" / "design-tokens" / "source"
GENERATED = ROOT / "nimble" / "design-tokens" / "generated"

PRIMITIVES_PATH = SOURCE / "primitives.json"
THEMES_PATH = SOURCE / "themes.json"
MOTION_PATH = SOURCE / "motion.json"

CSS_PATH = GENERATED / "nimble.tokens.css"
JSON_PATH = GENERATED / "nimble.tokens.json"
TS_PATH = GENERATED / "nimble.tokens.ts"

REFERENCE_PATTERN = re.compile(r"^\{([^}]+)\}$")


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def get_path(data: dict[str, Any], path: str) -> Any:
    current: Any = data

    for part in path.split("."):
        if not isinstance(current, dict) or part not in current:
            raise KeyError(f"Unknown token reference: {path}")
        current = current[part]

    return current


def resolve_value(value: Any, primitives: dict[str, Any]) -> Any:
    if not isinstance(value, str):
        return value

    match = REFERENCE_PATTERN.match(value)

    if not match:
        return value

    resolved = get_path(primitives, match.group(1))

    if isinstance(resolved, dict):
        raise TypeError(
            f"Token reference must resolve to a scalar: {value}"
        )

    return resolved


def resolve_tree(
    value: Any,
    primitives: dict[str, Any],
) -> Any:
    if isinstance(value, dict):
        return {
            key: resolve_tree(child, primitives)
            for key, child in value.items()
        }

    if isinstance(value, list):
        return [
            resolve_tree(child, primitives)
            for child in value
        ]

    return resolve_value(value, primitives)


def flatten(
    value: dict[str, Any],
    prefix: tuple[str, ...] = (),
) -> dict[str, Any]:
    flattened: dict[str, Any] = {}

    for key, child in value.items():
        path = prefix + (str(key),)

        if isinstance(child, dict):
            flattened.update(flatten(child, path))
        else:
            flattened["-".join(path)] = child

    return flattened


def css_name(name: str) -> str:
    normalized = re.sub(
        r"([a-z0-9])([A-Z])",
        r"\1-\2",
        name,
    )
    normalized = normalized.replace("_", "-")
    return normalized.lower()


def render_css(
    primitives: dict[str, Any],
    themes: dict[str, Any],
    motion: dict[str, Any],
) -> str:
    primitive_flat = flatten(primitives)
    motion_flat = flatten(motion)

    lines = [
        "/* Generated by compile_nimble_tokens.py. */",
        "/* Do not edit directly. */",
        "",
        ":root {",
    ]

    for name, value in sorted(primitive_flat.items()):
        lines.append(
            f"  --nimble-{css_name(name)}: {value};"
        )

    for name, value in sorted(motion_flat.items()):
        lines.append(
            f"  --nimble-{css_name(name)}: {value};"
        )

    lines.append("}")
    lines.append("")

    for theme_name, theme_values in themes.items():
        selector = (
            ':root, [data-nimble-theme="light"]'
            if theme_name == "light"
            else f'[data-nimble-theme="{theme_name}"]'
        )

        lines.append(f"{selector} {{")

        for name, value in sorted(flatten(theme_values).items()):
            lines.append(
                f"  --nimble-semantic-{css_name(name)}: {value};"
            )

        lines.append("}")
        lines.append("")

    lines.extend(
        [
            "@media (prefers-reduced-motion: reduce) {",
            "  :root {",
            "    --nimble-motion-duration-micro: 0ms;",
            "    --nimble-motion-duration-fast: 0ms;",
            "    --nimble-motion-duration-standard: 0ms;",
            "    --nimble-motion-duration-deliberate: 0ms;",
            "    --nimble-motion-duration-structural: 0ms;",
            "    --nimble-motion-duration-narrative: 0ms;",
            "    --nimble-motion-distance-micro: 0rem;",
            "    --nimble-motion-distance-small: 0rem;",
            "    --nimble-motion-distance-medium: 0rem;",
            "    --nimble-motion-distance-large: 0rem;",
            "    --nimble-motion-distance-spatial: 0rem;",
            "  }",
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def render_typescript(tokens: dict[str, Any]) -> str:
    payload = json.dumps(
        tokens,
        indent=2,
        sort_keys=True,
    )

    return (
        "/* Generated by compile_nimble_tokens.py. */\n"
        "/* Do not edit directly. */\n\n"
        f"export const nimbleTokens = {payload} as const;\n\n"
        "export type NimbleTokens = typeof nimbleTokens;\n"
    )


def main() -> None:
    GENERATED.mkdir(
        parents=True,
        exist_ok=True,
    )

    primitive_document = load_json(PRIMITIVES_PATH)
    theme_document = load_json(THEMES_PATH)
    motion_document = load_json(MOTION_PATH)

    primitives = {
        key: value
        for key, value in primitive_document.items()
        if key != "meta"
    }

    raw_themes = theme_document["themes"]
    raw_motion = motion_document["motion"]

    themes = {
        name: resolve_tree(values, primitives)
        for name, values in raw_themes.items()
    }

    compiled = {
        "meta": {
            "name": "Nimble Compiled Tokens",
            "version": "0.1.0",
            "generated": True
        },
        "primitives": primitives,
        "themes": themes,
        "motion": raw_motion
    }

    CSS_PATH.write_text(
        render_css(
            primitives,
            themes,
            {"motion": raw_motion},
        ),
        encoding="utf-8",
    )

    JSON_PATH.write_text(
        json.dumps(
            compiled,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    TS_PATH.write_text(
        render_typescript(compiled),
        encoding="utf-8",
    )

    print("=" * 72)
    print("NIMBLE™ TOKEN COMPILATION")
    print("=" * 72)
    print("Primitive groups:", len(primitives))
    print("Themes:", len(themes))
    print("Motion groups:", len(raw_motion))
    print("CSS:", CSS_PATH.relative_to(ROOT))
    print("JSON:", JSON_PATH.relative_to(ROOT))
    print("TypeScript:", TS_PATH.relative_to(ROOT))
    print("Status: PASS")


if __name__ == "__main__":
    main()
