APP_NAME = "CardHawk OS™"
APP_VERSION = "Alpha 2.3"
BUILD = "2026.06.xx"

SCHEMA_VERSION = "2.3.0"
PIPELINE_VERSION = "2.3.0"
DATABASE_VERSION = "2.3.0"

CANONICAL_ENGINE_PACKAGE = "engines"
DEPRECATED_ENGINE_PACKAGE = "engine"
CANONICAL_AEYE_PACKAGE = "hawk_aeye"
DEPRECATED_AEYE_PACKAGE = "cardhawk_aeye"
