from __future__ import annotations

import json
from pathlib import Path

from .models import GenesisPackagePlan, GenesisPackageResult


class GenesisConstructor:
    """
    Constructs a Genesis Package directory from a GenesisPackagePlan.

    This first implementation focuses on additive package skeletons.
    """

    def construct(
        self, plan: GenesisPackagePlan, output_root: Path
    ) -> GenesisPackageResult:
        spec = plan.spec
        package_root = output_root / spec.gp_id
        package_root.mkdir(parents=True, exist_ok=True)

        files_created: list[Path] = []

        def write(rel: str, content: str) -> None:
            path = package_root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            files_created.append(path)

        write("manifest.json", json.dumps(plan.manifest, indent=2))
        write("README.md", self._readme(plan))
        write("ENGINEERING_NOTES.md", self._engineering_notes(plan))
        write("VERIFY.md", self._verify(plan))
        write("ROLLBACK.md", self._rollback(plan))

        # Create placeholder files explicitly requested by the construction plan.
        for rel_path in spec.files_to_add:
            if rel_path.endswith("/"):
                (package_root / rel_path).mkdir(parents=True, exist_ok=True)
                continue
            placeholder = (
                f'"""Generated by Genesis Package {spec.gp_id}: {spec.title}."""\n'
            )
            write(rel_path, placeholder)

        return GenesisPackageResult(
            spec=spec,
            output_dir=package_root,
            files_created=files_created,
            ready=True,
            notes=["Genesis package constructed successfully."],
        )

    def _readme(self, plan: GenesisPackagePlan) -> str:
        spec = plan.spec
        return f"""# {spec.gp_id} — {spec.title}

Classification: {spec.classification.value}  
Authority: {spec.authority}  
Family: {spec.family}  
Risk: {spec.risk.value}

## Summary

{spec.summary}

## Merge Instruction

Follow the Integration Manifest. Do not replace the root `aletheus/` folder.
"""

    def _engineering_notes(self, plan: GenesisPackagePlan) -> str:
        spec = plan.spec
        return f"""# Engineering Notes — {spec.gp_id}

## Purpose

{spec.summary}

## Constitutional Role

Genesis Packages are constitutional construction artifacts. They should be ontology-aware, collision-checked, ADR-backed, Watch Tower-verifiable, and Repository DNA-recorded.

## Authority

{spec.authority}

## Family

{spec.family}
"""

    def _verify(self, plan: GenesisPackagePlan) -> str:
        steps = "\n".join(f"- [ ] {step}" for step in plan.verification_steps)
        return f"# Verification — {plan.spec.gp_id}\n\n{steps}\n"

    def _rollback(self, plan: GenesisPackagePlan) -> str:
        steps = "\n".join(f"- {step}" for step in plan.rollback_steps)
        return f"# Rollback — {plan.spec.gp_id}\n\n{steps}\n"
